from mainapp import models

def insertCountry():
	countries = []
	countries.append(models.Country(name="Afghanistan"))
	countries.append(models.Country(name="Albania"))
	countries.append(models.Country(name="Algeria"))
	countries.append(models.Country(name="American Samoa"))
	countries.append(models.Country(name="Andorra"))
	countries.append(models.Country(name="Angola"))
	countries.append(models.Country(name="Anguilla"))
	countries.append(models.Country(name="Antigua and Barbuda"))
	countries.append(models.Country(name="Argentina"))
	countries.append(models.Country(name="Armenia"))
	countries.append(models.Country(name="Aruba"))
	countries.append(models.Country(name="Australia"))
	countries.append(models.Country(name="Austria"))
	countries.append(models.Country(name="Azerbaijan"))
	countries.append(models.Country(name="Bahamas"))
	countries.append(models.Country(name="Bahrain"))
	countries.append(models.Country(name="Bangladesh"))
	countries.append(models.Country(name="Barbados"))
	countries.append(models.Country(name="Belarus"))
	countries.append(models.Country(name="Belgium"))
	countries.append(models.Country(name="Belize"))
	countries.append(models.Country(name="Benin"))
	countries.append(models.Country(name="Bermuda"))
	countries.append(models.Country(name="Bhutan"))
	countries.append(models.Country(name="Bolivia"))
	countries.append(models.Country(name="Bosnia-Herzegovina"))
	countries.append(models.Country(name="Botswana"))
	countries.append(models.Country(name="Bouvet Island"))
	countries.append(models.Country(name="Brazil"))
	countries.append(models.Country(name="Brunei"))
	countries.append(models.Country(name="Bulgaria"))
	countries.append(models.Country(name="Burkina Faso"))
	countries.append(models.Country(name="Burundi"))
	countries.append(models.Country(name="Cambodia"))
	countries.append(models.Country(name="Cameroon"))
	countries.append(models.Country(name="Canada"))
	countries.append(models.Country(name="Cape Verde"))
	countries.append(models.Country(name="Cayman Islands"))
	countries.append(models.Country(name="Central African Republic"))
	countries.append(models.Country(name="Chad"))
	countries.append(models.Country(name="Chile"))
	countries.append(models.Country(name="China"))
	countries.append(models.Country(name="Christmas Island"))
	countries.append(models.Country(name="Cocos (Keeling) Islands"))
	countries.append(models.Country(name="Colombia"))
	countries.append(models.Country(name="Comoros"))
	countries.append(models.Country(name="Congo, Democratic Republic of the (Zaire)"))
	countries.append(models.Country(name="Congo, Republic of"))
	countries.append(models.Country(name="Cook Islands"))
	countries.append(models.Country(name="Costa Rica"))
	countries.append(models.Country(name="Croatia"))
	countries.append(models.Country(name="Cuba"))
	countries.append(models.Country(name="Cyprus"))
	countries.append(models.Country(name="Czech Republic"))
	countries.append(models.Country(name="Denmark"))
	countries.append(models.Country(name="Djibouti"))
	countries.append(models.Country(name="Dominica"))
	countries.append(models.Country(name="Dominican Republic"))
	countries.append(models.Country(name="Ecuador"))
	countries.append(models.Country(name="Egypt"))
	countries.append(models.Country(name="El Salvador"))
	countries.append(models.Country(name="Equatorial Guinea"))
	countries.append(models.Country(name="Eritrea"))
	countries.append(models.Country(name="Estonia"))
	countries.append(models.Country(name="Ethiopia"))
	countries.append(models.Country(name="Falkland Islands"))
	countries.append(models.Country(name="Faroe Islands"))
	countries.append(models.Country(name="Fiji"))
	countries.append(models.Country(name="Finland"))
	countries.append(models.Country(name="France"))
	countries.append(models.Country(name="French Guiana"))
	countries.append(models.Country(name="Gabon"))
	countries.append(models.Country(name="Gambia"))
	countries.append(models.Country(name="Georgia"))
	countries.append(models.Country(name="Germany"))
	countries.append(models.Country(name="Ghana"))
	countries.append(models.Country(name="Gibraltar"))
	countries.append(models.Country(name="Greece"))
	countries.append(models.Country(name="Greenland"))
	countries.append(models.Country(name="Grenada"))
	countries.append(models.Country(name="Guadeloupe (French)"))
	countries.append(models.Country(name="Guam (USA)"))
	countries.append(models.Country(name="Guatemala"))
	countries.append(models.Country(name="Guinea"))
	countries.append(models.Country(name="Guinea Bissau"))
	countries.append(models.Country(name="Guyana"))
	countries.append(models.Country(name="Haiti"))
	countries.append(models.Country(name="Holy See"))
	countries.append(models.Country(name="Honduras"))
	countries.append(models.Country(name="Hong Kong"))
	countries.append(models.Country(name="Hungary"))
	countries.append(models.Country(name="Iceland"))
	countries.append(models.Country(name="India"))
	countries.append(models.Country(name="Indonesia"))
	countries.append(models.Country(name="Iran"))
	countries.append(models.Country(name="Iraq"))
	countries.append(models.Country(name="Ireland"))
	countries.append(models.Country(name="Israel"))
	countries.append(models.Country(name="Italy"))
	countries.append(models.Country(name="Ivory Coast (Cote D`Ivoire)"))
	countries.append(models.Country(name="Jamaica"))
	countries.append(models.Country(name="Japan"))
	countries.append(models.Country(name="Jordan"))
	countries.append(models.Country(name="Kazakhstan"))
	countries.append(models.Country(name="Kenya"))
	countries.append(models.Country(name="Kiribati"))
	countries.append(models.Country(name="Kuwait"))
	countries.append(models.Country(name="Kyrgyzstan"))
	countries.append(models.Country(name="Laos"))
	countries.append(models.Country(name="Latvia"))
	countries.append(models.Country(name="Lebanon"))
	countries.append(models.Country(name="Lesotho"))
	countries.append(models.Country(name="Liberia"))
	countries.append(models.Country(name="Libya"))
	countries.append(models.Country(name="Liechtenstein"))
	countries.append(models.Country(name="Lithuania"))
	countries.append(models.Country(name="Luxembourg"))
	countries.append(models.Country(name="Macau"))
	countries.append(models.Country(name="Macedonia"))
	countries.append(models.Country(name="Madagascar"))
	countries.append(models.Country(name="Malawi"))
	countries.append(models.Country(name="Malaysia"))
	countries.append(models.Country(name="Maldives"))
	countries.append(models.Country(name="Mali"))
	countries.append(models.Country(name="Malta"))
	countries.append(models.Country(name="Marshall Islands"))
	countries.append(models.Country(name="Martinique (French)"))
	countries.append(models.Country(name="Mauritania"))
	countries.append(models.Country(name="Mauritius"))
	countries.append(models.Country(name="Mayotte"))
	countries.append(models.Country(name="Mexico"))
	countries.append(models.Country(name="Micronesia"))
	countries.append(models.Country(name="Moldova"))
	countries.append(models.Country(name="Monaco"))
	countries.append(models.Country(name="Mongolia"))
	countries.append(models.Country(name="Montenegro"))
	countries.append(models.Country(name="Montserrat"))
	countries.append(models.Country(name="Morocco"))
	countries.append(models.Country(name="Mozambique"))
	countries.append(models.Country(name="Myanmar"))
	countries.append(models.Country(name="Namibia"))
	countries.append(models.Country(name="Nauru"))
	countries.append(models.Country(name="Nepal"))
	countries.append(models.Country(name="Netherlands"))
	countries.append(models.Country(name="Netherlands Antilles"))
	countries.append(models.Country(name="New Caledonia (French)"))
	countries.append(models.Country(name="New Zealand"))
	countries.append(models.Country(name="Nicaragua"))
	countries.append(models.Country(name="Niger"))
	countries.append(models.Country(name="Nigeria"))
	countries.append(models.Country(name="Niue"))
	countries.append(models.Country(name="Norfolk Island"))
	countries.append(models.Country(name="North Korea"))
	countries.append(models.Country(name="Northern Mariana Islands"))
	countries.append(models.Country(name="Norway"))
	countries.append(models.Country(name="Oman"))
	countries.append(models.Country(name="Pakistan"))
	countries.append(models.Country(name="Palau"))
	countries.append(models.Country(name="Panama"))
	countries.append(models.Country(name="Papua New Guinea"))
	countries.append(models.Country(name="Paraguay"))
	countries.append(models.Country(name="Peru"))
	countries.append(models.Country(name="Philippines"))
	countries.append(models.Country(name="Pitcairn Island"))
	countries.append(models.Country(name="Poland"))
	countries.append(models.Country(name="Polynesia (French)"))
	countries.append(models.Country(name="Portugal"))
	countries.append(models.Country(name="Puerto Rico"))
	countries.append(models.Country(name="Qatar"))
	countries.append(models.Country(name="Reunion"))
	countries.append(models.Country(name="Romania"))
	countries.append(models.Country(name="Russia"))
	countries.append(models.Country(name="Rwanda"))
	countries.append(models.Country(name="Saint Helena"))
	countries.append(models.Country(name="Saint Kitts and Nevis"))
	countries.append(models.Country(name="Saint Lucia"))
	countries.append(models.Country(name="Saint Pierre and Miquelon"))
	countries.append(models.Country(name="Saint Vincent and Grenadines"))
	countries.append(models.Country(name="Samoa"))
	countries.append(models.Country(name="San Marino"))
	countries.append(models.Country(name="Sao Tome and Principe"))
	countries.append(models.Country(name="Saudi Arabia"))
	countries.append(models.Country(name="Senegal"))
	countries.append(models.Country(name="Serbia"))
	countries.append(models.Country(name="Seychelles"))
	countries.append(models.Country(name="Sierra Leone"))
	countries.append(models.Country(name="Singapore"))
	countries.append(models.Country(name="Slovakia"))
	countries.append(models.Country(name="Slovenia"))
	countries.append(models.Country(name="Solomon Islands"))
	countries.append(models.Country(name="Somalia"))
	countries.append(models.Country(name="South Africa"))
	countries.append(models.Country(name="South Georgia and South Sandwich Islands"))
	countries.append(models.Country(name="South Korea"))
	countries.append(models.Country(name="South Sudan"))
	countries.append(models.Country(name="Spain"))
	countries.append(models.Country(name="Sri Lanka"))
	countries.append(models.Country(name="Sudan"))
	countries.append(models.Country(name="Suriname"))
	countries.append(models.Country(name="Svalbard and Jan Mayen Islands"))
	countries.append(models.Country(name="Swaziland"))
	countries.append(models.Country(name="Sweden"))
	countries.append(models.Country(name="Switzerland"))
	countries.append(models.Country(name="Syria"))
	countries.append(models.Country(name="Taiwan"))
	countries.append(models.Country(name="Tajikistan"))
	countries.append(models.Country(name="Tanzania"))
	countries.append(models.Country(name="Thailand"))
	countries.append(models.Country(name="Timor-Leste (East Timor)"))
	countries.append(models.Country(name="Togo"))
	countries.append(models.Country(name="Tokelau"))
	countries.append(models.Country(name="Tonga"))
	countries.append(models.Country(name="Trinidad and Tobago"))
	countries.append(models.Country(name="Tunisia"))
	countries.append(models.Country(name="Turkey"))
	countries.append(models.Country(name="Turkmenistan"))
	countries.append(models.Country(name="Turks and Caicos Islands"))
	countries.append(models.Country(name="Tuvalu"))
	countries.append(models.Country(name="Uganda"))
	countries.append(models.Country(name="Ukraine"))
	countries.append(models.Country(name="United Arab Emirates"))
	countries.append(models.Country(name="United Kingdom"))
	countries.append(models.Country(name="United States"))
	countries.append(models.Country(name="Uruguay"))
	countries.append(models.Country(name="Uzbekistan"))
	countries.append(models.Country(name="Vanuatu"))
	countries.append(models.Country(name="Venezuela"))
	countries.append(models.Country(name="Vietnam"))
	countries.append(models.Country(name="Virgin Islands"))
	countries.append(models.Country(name="Wallis and Futuna Islands"))
	countries.append(models.Country(name="Yemen"))
	countries.append(models.Country(name="Zambia"))
	countries.append(models.Country(name="Zimbabwe"))

	for country in countries :
		country.save()

def insertTimezone():
	timezones = []

	timezones.append(models.Timezone(name="(GMT-12:00) International Date Line West",offset=-12))
	timezones.append(models.Timezone(name="(GMT-11:00) Midway Island, Samoa",offset=-11))
	timezones.append(models.Timezone(name="(GMT-10:00) Hawaii",offset=-10))
	timezones.append(models.Timezone(name="(GMT-09:00) Alaska",offset=-9))
	timezones.append(models.Timezone(name="(GMT-08:00) Pacific Time (US and Canada); Tijuana",offset=-8))
	timezones.append(models.Timezone(name="(GMT-07:00) Mountain Time (US and Canada)",offset=-7))
	timezones.append(models.Timezone(name="(GMT-07:00) Chihuahua, La Paz, Mazatlan",offset=-7))
	timezones.append(models.Timezone(name="(GMT-07:00) Arizona",offset=-7))
	timezones.append(models.Timezone(name="(GMT-06:00) Central Time (US and Canada",offset=-6))
	timezones.append(models.Timezone(name="(GMT-06:00) Saskatchewan",offset=-6))
	timezones.append(models.Timezone(name="(GMT-06:00) Guadalajara, Mexico City, Monterrey",offset=-6))
	timezones.append(models.Timezone(name="(GMT-06:00) Central America",offset=-6))
	timezones.append(models.Timezone(name="(GMT-05:00) Eastern Time (US and Canada)",offset=-5))
	timezones.append(models.Timezone(name="(GMT-05:00) Indiana (East)",offset=-5))
	timezones.append(models.Timezone(name="(GMT-05:00) Bogota, Lima, Quito",offset=-5))
	timezones.append(models.Timezone(name="(GMT-04:00) Atlantic Time (Canada)",offset=-4))
	timezones.append(models.Timezone(name="(GMT-04:00) Caracas, La Paz",offset=-4))
	timezones.append(models.Timezone(name="(GMT-04:00) Santiago",offset=-4))
	timezones.append(models.Timezone(name="(GMT-03:30) Newfoundland and Labrador",offset=-3))
	timezones.append(models.Timezone(name="(GMT-03:00) Brasilia",offset=-3))
	timezones.append(models.Timezone(name="(GMT-03:00) Buenos Aires, Georgetown",offset=-3))
	timezones.append(models.Timezone(name="(GMT-03:00) Greenland",offset=-3))
	timezones.append(models.Timezone(name="(GMT-02:00) Mid-Atlantic",offset=-2))
	timezones.append(models.Timezone(name="(GMT-01:00) Azores",offset=-1))
	timezones.append(models.Timezone(name="(GMT-01:00) Cape Verde Islands",offset=-1))
	timezones.append(models.Timezone(name="(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London",offset=0))
	timezones.append(models.Timezone(name="(GMT) Casablanca, Monrovia",offset=0))
	timezones.append(models.Timezone(name="(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",offset=1))
	timezones.append(models.Timezone(name="(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb",offset=1))
	timezones.append(models.Timezone(name="(GMT+01:00) Brussels, Copenhagen, Madrid, Paris",offset=1))
	timezones.append(models.Timezone(name="(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",offset=1))
	timezones.append(models.Timezone(name="(GMT+01:00) West Central Africa",offset=1))
	timezones.append(models.Timezone(name="(GMT+02:00) Bucharest",offset=2))
	timezones.append(models.Timezone(name="(GMT+02:00) Cairo",offset=2))
	timezones.append(models.Timezone(name="(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",offset=2))
	timezones.append(models.Timezone(name="(GMT+02:00) Athens, Istanbul, Minsk",offset=2))
	timezones.append(models.Timezone(name="(GMT+02:00) Jerusalem",offset=2))
	timezones.append(models.Timezone(name="(GMT+02:00) Harare, Pretoria",offset=2))
	timezones.append(models.Timezone(name="(GMT+03:00) Moscow, St. Petersburg, Volgograd",offset=3))
	timezones.append(models.Timezone(name="(GMT+03:00) Kuwait, Riyadh",offset=3))
	timezones.append(models.Timezone(name="(GMT+03:00) Nairobi",offset=3))
	timezones.append(models.Timezone(name="(GMT+03:00) Baghdad",offset=3))
	timezones.append(models.Timezone(name="(GMT+03:30) Tehran",offset=3))
	timezones.append(models.Timezone(name="(GMT+04:00) Abu Dhabi, Muscat",offset=4))
	timezones.append(models.Timezone(name="(GMT+04:00) Baku, Tbilisi, Yerevan",offset=4))
	timezones.append(models.Timezone(name="(GMT+04:30) Kabul",offset=4))
	timezones.append(models.Timezone(name="(GMT+05:00) Ekaterinburg",offset=5))
	timezones.append(models.Timezone(name="(GMT+05:00) Islamabad, Karachi, Tashkent",offset=5))
	timezones.append(models.Timezone(name="(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",offset=5))
	timezones.append(models.Timezone(name="(GMT+05:45) Kathmandu",offset=5))
	timezones.append(models.Timezone(name="(GMT+06:00) Astana, Dhaka",offset=6))
	timezones.append(models.Timezone(name="(GMT+06:00) Sri Jayawardenepura",offset=6))
	timezones.append(models.Timezone(name="(GMT+06:00) Almaty, Novosibirsk",offset=6))
	timezones.append(models.Timezone(name="(GMT+06:30) Yangon Rangoon",offset=6))
	timezones.append(models.Timezone(name="(GMT+07:00) Bangkok, Hanoi, Jakarta",offset=7))
	timezones.append(models.Timezone(name="(GMT+07:00) Krasnoyarsk",offset=7))
	timezones.append(models.Timezone(name="(GMT+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",offset=8))
	timezones.append(models.Timezone(name="(GMT+08:00) Kuala Lumpur, Singapore",offset=8))
	timezones.append(models.Timezone(name="(GMT+08:00) Taipei",offset=8))
	timezones.append(models.Timezone(name="(GMT+08:00) Perth",offset=8))
	timezones.append(models.Timezone(name="(GMT+08:00) Irkutsk, Ulaanbaatar",offset=8))
	timezones.append(models.Timezone(name="(GMT+09:00) Seoul",offset=9))
	timezones.append(models.Timezone(name="(GMT+09:00) Osaka, Sapporo, Tokyo",offset=9))
	timezones.append(models.Timezone(name="(GMT+09:00) Yakutsk",offset=9))
	timezones.append(models.Timezone(name="(GMT+09:30) Darwin",offset=9))
	timezones.append(models.Timezone(name="(GMT+09:30) Adelaide",offset=9))
	timezones.append(models.Timezone(name="(GMT+10:00) Canberra, Melbourne, Sydney",offset=10))
	timezones.append(models.Timezone(name="(GMT+10:00) Brisbane",offset=10))
	timezones.append(models.Timezone(name="(GMT+10:00) Hobart",offset=10))
	timezones.append(models.Timezone(name="(GMT+10:00) Vladivostok",offset=10))
	timezones.append(models.Timezone(name="(GMT+10:00) Guam, Port Moresby",offset=10))
	timezones.append(models.Timezone(name="(GMT+11:00) Magadan, Solomon Islands, New Caledonia",offset=11))
	timezones.append(models.Timezone(name="(GMT+12:00) Fiji Islands, Kamchatka, Marshall Islands",offset=12))
	timezones.append(models.Timezone(name="(GMT+12:00) Auckland, Wellington",offset=12))
	timezones.append(models.Timezone(name="(GMT+13:00) Nuku'alofa",offset=13))

	for timezone in timezones :
		timezone.save()